#!/bin/bash

# Deploy ke Cloudflare Pages - elc-website-blv
# Ini akan menginstruksikan Anda cara deploy

echo "=========================================="
echo "🚀 DEPLOY KE CLOUDFLARE PAGES"
echo "=========================================="
echo ""
echo "Project sudah siap untuk deploy ke:"
echo "🌐 https://elc-website-blv.pages.dev"
echo ""
echo "=========================================="
echo "CARA CEPAT:"
echo "=========================================="
echo ""
echo "1. Login ke Cloudflare Dashboard:"
echo "   https://dash.cloudflare.com/"
echo ""
echo "2. Go to Pages"
echo ""
echo "3. Klik 'Upload assets'"
echo ""
echo "4. Upload folder: .next/static"
echo ""
echo "Atau untuk automatic deployment lebih mudah:"
echo ""
echo "1. Connect GitHub ke Cloudflare Pages"
echo "   - Repository: https://github.com/aris2394/webelc"
echo "   - Build: npm run build"
echo "   - Output: .next"
echo ""
echo "=========================================="
echo "✅ Build sudah selesai!"
echo "Output: /var/www/html/elc-baru/.next"
echo "=========================================="
